device: Device Name # Name of the device that is emulated
name: Test 1 # Name of this configuration
protocol: text_hex # Protocol used in this test, 'text' to only support text protocol, 'text_hex' to support both text and hex protocols, 'hex' to only support hex protocol
version: 0x4147 # Firmware version, optional if not using hex protocol
product_id: 0xA04C # Product ID, optional if not using hex protocol
bootloader: 0x51FA51FA51FA51FA51FA # Payload required to enter boot mode, false by default to disable 'boot' command

preset: vedirect_330 # The preset to use
preset_fields: # These fields are 'imported' from the specified preset
  - v: default # Can be either default, random or fuzzing. With default, the fixed default value of the field will be returned, random will generate random values and fuzzing will generate fuzzing values like boundary values
  - v1: fuzzing
    override: # One can use override to use the field properties of a preset but override certain properties
      values:
        - type: IntRandom
          amount: 8
          min: 0
          max: 10
      invalid: []
  - h1: default

fields: # Fields for text protocol
  - name: Voltage # Human readable name of the field
    key: V # Key of the field used in the text protocol
    units: mV # Unit of the field
    scale: 0.1 # Scale of the field
    interval: 2 # Default is 1; indicates the interval in seconds between the generation of new values. This property is only used when the emulator is run in timed mode.
    values: # List of scenarios used to generate values for the field
      - type: IntRandom # Scenario type
        amount: 8 # Number of values that are generated using this scenario; can be left out to generate infinite values
        min: 0 # Specific property to IntRandom, see docstrings in the scenarios for more detailed explanation of all the properties
        max: 10
      - type: IntRandom # Once 8 random integers between 0-10 have been generated, the emulator will move to this scenario
        amount: 3
        min: -10
        max: 0
      - type: IntRandom
        amount: 5
        min: 100
        max: 500
      - type: Loop # Loop can be used to generate a sequence of values multiple times
        amount: 1
        values:
          - type: Loop # You can add loops inside loops
            amount: 2
            values:
            - type: IntFixed
              amount: 2
              value: 1
            - type: IntFixed
              amount: 2
              value: 2
          - type: IntFixed
            amount: 2
            value: 3
  - name: Amperage
    key: A
    units: mA
    values:
      - type: IntRandom
        amount: 4
        min: 0
        max: 5
  - name: Test
    key: T
    units: T
    values:
      - type: Arithmetic # Arithemtic can be used to generate values based on the value of other values
        value: V * A * 100 # Any referenced fields used here should be defined above the Arithmetic field
  - name: Auxiliary (starter) voltage
    key: VS
    unit: mV
    values:
      - type: Loop
        amount: 1 # Amount of times to loop, -1 to loop infinitely
        values:
          - type: Gradient
            gradient_type: linear
            step_size: 1
            min: 0
            max: 10
          - type: Loop
            amount: 1
            values:
              - type: IntBoundary
                amount: 1
                seed: 0 # You can specify a seed to use a different seed than the global seed for this field
                min: 0
                max: 10

hex_fields: # Fields for hex protocol
  - name: Voltage # A hex field is similar to a text field
    key: 0x1234 # The only difference is that the key is now a hexadecimal value
    unit: mV
    values:
      - type: IntBoundary
        bits: 32 # For hex fields, a bit size needs to be given
        signed: true # An integer can be indicated as signed when using hex
        min: 0x00
        max: 0xFF
        writable: true # false by default, if true, this field is able to be updated using the hex 'set' command
        async_change: true # false by default, send this field as async message when it changes
        async_interval: 5 # false by default, send this field as async message at a set interval in seconds
      - type: IntRandom
        bits: 8
        amount: 0
        min: 0x00
        max: 0xFF
      - type: IntFixed
        bits: 8
        value: 0x0A
      - type: IntChoice
        bits: 8
        choices: [0x00, 0x01, 0x02]
      # And all other fields available in text protocol, fields will be encoded as hex
  - name: VS
    key: 0x1235
    unit: mV
    values:
      - type: IntFixed
        value: 0x0A
        bits: 8
        writable: true
