device: MPPT # Name of the device
name: Test 1 # Name of the test
protocol: text # Protocol used in this test, 'text' to only support text protocol, 'text_hex' to support both text and hex protocols, 'hex' to only support hex protocol
version: 0x4147 # Firmware version, optional if not using hex protocol
product_id: 0xA04C # Product ID, optional if not using hex protocol
bootloader: 0x51FA51FA51FA51FA51FA # Payload required to enter boot mode, false by default to disable 'boot' command

preset: vedirect_330

preset_fields:
  - v:      random
  - vpv:    random
  - ppv:    random
  - i:      random
  - il:     random
  - load:   random
  - relay:  random
  - h19:    random
  - h20:    random
  - h21:    random
  - h22:    random
  - h23:    random
  - err:    random
  - fw:     random
  - pid:    random
  - ser:    random
  - hsds:   random
  - ttg:    fuzzing
#preset_fields:
#  - v:      random
#  - vpv:    random
#  - ppv:    random
#  - i:      random
#  - il:     random
#  - load:   random
#  - relay:  default
#  - h19:    default
#  - h20:    default
#  - h21:    default
#  - h22:    default
#  - h23:    default
#  - err:    default
#  - fw:     default
#  - pid:    default
#  - ser:    default
#  - hsds:   default
fields:
  - name: Test
    key: T
    units: T
    values:
      - type: Arithmetic
        value: V * VPV * 100